In [2]:
import numpy as np

In [4]:
a = [1,2,3,4,5]
b = []
for i in a:
    
    b.append(i*2)
    
print(b)

[2, 4, 6, 8, 10]


In [6]:
a = np.array([1,2,3,4,5])
a*2

array([ 2,  4,  6,  8, 10])

In [7]:
a.ndim

1

In [47]:
d = np.array([[[[1],1],1],1])
print(d.shape)
print(d.ndim)

(2,)
1


In [48]:
d = np.array([[[[1]]]])
print(d.shape)
print(d.ndim)

(1, 1, 1, 1)
4


In [49]:
e = np.arange(40)
e = e.reshape(2,2,2,5)
print(e)
print(e.shape)
print(e.ndim)

[[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]]

  [[10 11 12 13 14]
   [15 16 17 18 19]]]


 [[[20 21 22 23 24]
   [25 26 27 28 29]]

  [[30 31 32 33 34]
   [35 36 37 38 39]]]]
(2, 2, 2, 5)
4


In [65]:
m1 = np.arange(12).reshape(4,3)
m2 = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
m1*m2                                                # this is a mirror multiplication

array([[  0,   2,   6],
       [ 12,  20,  30],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [69]:
m1 = np.arange(12).reshape(3,4)
m2 = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
m1@m2                                                      #This is a Row and Column multplication

array([[ 43,  49,  55],
       [123, 145, 167],
       [203, 241, 279]])

In [70]:
np.dot(m1,m2)                     # This is a Row and Column multiplication

array([[ 43,  49,  55],
       [123, 145, 167],
       [203, 241, 279]])

In [72]:
m1.dot(m2)                      # This is a Row and Column multiplication

array([[ 43,  49,  55],
       [123, 145, 167],
       [203, 241, 279]])

In [74]:
m1 = np.arange(12).reshape(4,3)
m2 = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
m1+m2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [12, 14, 16],
       [18, 20, 22]])

In [76]:
m1 = np.arange(12).reshape(4,3)
m2 = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
m1-m2

array([[-1, -1, -1],
       [-1, -1, -1],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [77]:
m1 = np.arange(12).reshape(4,3)
m2 = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
m1/m2

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        ]])

In [84]:
a = np.array([1,2,3,4],np.float16)
a

array([1., 2., 3., 4.], dtype=float16)

In [85]:
a.astype(np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [88]:
np.asarray(a,np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [94]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [96]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [97]:
np.empty(6)

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313, 1.48539705e-313,
       1.90979621e-313, 2.33419537e-313])

In [101]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [106]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [108]:
ar = np.array([1,2,3,4,5])

In [110]:
ar[2:4]

array([3, 4])

In [111]:
ar = np.arange(1,37).reshape(6,6)
ar

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [117]:
ar[1][0]

7

In [118]:
ar[3:5][1:7]

array([[25, 26, 27, 28, 29, 30]])