In [1]:
import numpy as np 
import pandas as pd

In [2]:
arr = np.arange(50).reshape((2,5,5))

In [3]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [4]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [5]:
arr[0:1,2:3,1:2]

array([[[11]]])

In [6]:
arr1 = np.arange(16).reshape((4,4))
arr1.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]], dtype=int32)

In [7]:
arr.sum(axis=0)

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

In [8]:
arr2 = np.arange(36).reshape((3,3,2,2))
arr2

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35]]]])

In [9]:
 np.empty((4,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.89812620e-307],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 2.04712907e-306,
        3.49698923e-317]])

In [10]:
arr>3

array([[[False, False, False, False,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [11]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])

In [12]:
[1,2,3,4] + [1,2,3,4]

[1, 2, 3, 4, 1, 2, 3, 4]

In [13]:
np.array([1,2,3,4]) + np.array([1,2,3,4])

array([2, 4, 6, 8])

In [14]:
one  = np.ones((5,5))

In [15]:
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
one  = np.ones((5,5))
one[0:,0:] = 0
one

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
one

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
r = [1,2,3,4,5,6]

In [19]:
r[-5:-1]

[2, 3, 4, 5]

In [20]:
len(r)

6

In [21]:
arr = np.array(['bob','jhon','bob','micky','anthony','jhon','bob','falcom'])
arr

array(['bob', 'jhon', 'bob', 'micky', 'anthony', 'jhon', 'bob', 'falcom'],
      dtype='<U7')

In [22]:
arr[arr == 'jhon']

array(['jhon', 'jhon'], dtype='<U7')

In [23]:
arr == 'jhon'

array([False,  True, False, False, False,  True, False, False])

In [24]:
arr <= "jhon"

array([ True,  True,  True, False,  True,  True,  True,  True])

In [25]:
data = np.random.randn(8)
data[arr=='jhon']

array([ 0.1827204 , -1.23430657])

In [26]:
data

array([-0.29673411,  0.1827204 ,  0.86479287,  0.23323257,  0.66340616,
       -1.23430657,  1.12691664, -0.47134405])

In [27]:
data[data<0] = 0
data

array([0.        , 0.1827204 , 0.86479287, 0.23323257, 0.66340616,
       0.        , 1.12691664, 0.        ])

In [28]:
np.arange(27).reshape((3,3,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [29]:
import matplotlib.pyplot as plt
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

Text(0.5, 1.0, 'Image plot of $\\sqrt{x^2 + y^2}$ for a grid of values')

In [30]:
r = [1.2,3.2,0.4,-2.5,-9.5]
np.absolute(r)

array([1.2, 3.2, 0.4, 2.5, 9.5])

In [31]:
r = np.array(r)
np.where(r>1,'greater than one','lesser than one')

array(['greater than one', 'greater than one', 'lesser than one',
       'lesser than one', 'lesser than one'], dtype='<U16')

In [32]:
r

array([ 1.2,  3.2,  0.4, -2.5, -9.5])

In [33]:
s = r>1

In [34]:
s

array([ True,  True, False, False, False])

In [35]:
s.any()

True

In [36]:
s.all()

False

In [37]:
r[r>1]

array([1.2, 3.2])

In [38]:
r[r<=1]

array([ 0.4, -2.5, -9.5])

In [39]:
print(r)
print(r[[True,False,True,False,True]])

[ 1.2  3.2  0.4 -2.5 -9.5]
[ 1.2  0.4 -9.5]


In [40]:
np.where( r<0,True,False)

array([False, False, False,  True,  True])

In [41]:
np.save('g.txt',r)

In [42]:
e = np.load('g.txt.npy')
e

array([ 1.2,  3.2,  0.4, -2.5, -9.5])

In [43]:
np.savez('f.txt',x = r)

In [44]:
np.savez_compressed('numpyfile.txt',r)

In [45]:
y = np.load('f.txt.npz')
y['x']

array([ 1.2,  3.2,  0.4, -2.5, -9.5])

In [46]:
sqar = np.arange(8)#.reshape((4,2))
sqar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
np.diag(sqar)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 7]])

In [48]:
square = np.diag(np.array([1,2,3]))

In [49]:
square[0,2] = 9
square

array([[1, 0, 9],
       [0, 2, 0],
       [0, 0, 3]])

In [50]:
np.transpose(square)

array([[1, 0, 0],
       [0, 2, 0],
       [9, 0, 3]])

In [51]:
square.compress

<function ndarray.compress>

In [52]:
nwalks = 5
nsteps = 4
np.random.randint(0, 3, size=(nwalks, nsteps))

array([[0, 2, 1, 1],
       [2, 1, 0, 1],
       [1, 1, 2, 0],
       [0, 2, 1, 1],
       [0, 2, 0, 0]])

In [53]:
arr = np.arange(9).reshape((3,3))
np.where(arr[:,-1:]>4,'greater than 4','lesser than 4')


array([['lesser than 4'],
       ['greater than 4'],
       ['greater than 4']], dtype='<U14')

In [54]:
dic = pd.Series(data=[0,1,2,3,4,5],index=['zero','one','two','three','four','five'])
dic

zero     0
one      1
two      2
three    3
four     4
five     5
dtype: int64

In [55]:
dic.append(pd.Series([6,7],index=['six','seven']))

zero     0
one      1
two      2
three    3
four     4
five     5
six      6
seven    7
dtype: int64

In [56]:
dic['six'] = 6
dic.name = 'numbers'


In [57]:
dframe = pd.DataFrame(dic)

In [58]:
dframe = pd.DataFrame(data=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],
                      index=['1-4','5-8','9-12','13-16'],
                      columns=[0,1,2,3])
dframe

0   1   2   3
1-4     1   2   3   4
5-8     5   6   7   8
9-12    9  10  11  12
13-16  13  14  15  16

In [59]:
player_data = pd.DataFrame({'tony':[1,2,3,4],'robins':[1,2,3,4],'jack':[1,2,3,4],'ronnie':[1,2,3,4]},
            index = ['health','speed','height','age'])

In [60]:
player_data = player_data.transpose()

In [61]:
player_data

health  speed  height  age
tony         1      2       3    4
robins       1      2       3    4
jack         1      2       3    4
ronnie       1      2       3    4

In [62]:
player_data.loc['tony'] = ['87%','20kph','5.8ft','24']

In [63]:
player_data.loc['robins':'ronnie'] = [['80%','17kph','5.9ft','25'],['90%','30kph','5.5ft','22'],
                                     ['95%','32kph','5.7ft','21']]

In [64]:
player_data

health  speed height age
tony      87%  20kph  5.8ft  24
robins    80%  17kph  5.9ft  25
jack      90%  30kph  5.5ft  22
ronnie    95%  32kph  5.7ft  21

In [65]:
player_data.index.name = 'players'
player_data.loc['oliver'] = ['98%','35kph','5.8ft','34']

In [66]:
player_data

health  speed height age
players                         
tony       87%  20kph  5.8ft  24
robins     80%  17kph  5.9ft  25
jack       90%  30kph  5.5ft  22
ronnie     95%  32kph  5.7ft  21
oliver     98%  35kph  5.8ft  34

In [67]:
player_data['personality'] = player_data['age'] == '24'

In [68]:
 del player_data['personality']

In [69]:
del player_data.index.name
player_data

health  speed height age
tony      87%  20kph  5.8ft  24
robins    80%  17kph  5.9ft  25
jack      90%  30kph  5.5ft  22
ronnie    95%  32kph  5.7ft  21
oliver    98%  35kph  5.8ft  34

In [70]:
player_data = pd.DataFrame({'tony':[1,2,3,4],'robins':[1,2,3,4],'jack':[1,2,3,4],'ronnie':[1,2,3,4]},
            index = ['health','speed','height','age'])

player_data = player_data.transpose()
player_data.loc['tony'] = [87,20,5.8,24]
player_data.loc['robins':'ronnie'] = [[80,17,5.9,25],[90,30,5.5,22],
                                     [95,32,5.7,21]]


In [71]:
player_data

health  speed  height  age
tony        87     20     5.8   24
robins      80     17     5.9   25
jack        90     30     5.5   22
ronnie      95     32     5.7   21

In [73]:
player_data['health'].loc['robins'] = 80

c:\users\mu_vi\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


In [74]:
r =  player_data.loc['tony':].sum(axis = 1) >140
player_data['personality'] = ['good' if i==True else 'average' for i in r]
player_data

health  speed  height  age personality
tony        87     20     5.8   24     average
robins      80     17     5.9   25     average
jack        90     30     5.5   22        good
ronnie      95     32     5.7   21        good

In [75]:
player_data.reindex(['robins','tony','jack','jill'])

health  speed  height   age personality
robins    80.0   17.0     5.9  25.0     average
tony      87.0   20.0     5.8  24.0     average
jack      90.0   30.0     5.5  22.0        good
jill       NaN    NaN     NaN   NaN         NaN

In [76]:
player_data.loc[['robins','tony'],['health','personality']]

health personality
robins      80     average
tony        87     average

In [77]:
player_data.loc['tony':].sum(axis=1)

tony      136.8
robins    127.9
jack      147.5
ronnie    153.7
dtype: float64

In [82]:
player_data[[True,True,False,True]]

health  speed  height  age personality
tony        87     20     5.8   24     average
robins      80     17     5.9   25     average
ronnie      95     32     5.7   21        good

In [117]:
player_data['health']>80

tony       True
robins    False
jack       True
ronnie     True
Name: health, dtype: bool

In [134]:
player_data.loc['robins']['health':]

health              80
speed               17
height             5.9
age                 25
personality    average
Name: robins, dtype: object